services:
  server:
    build:
      context: .
      dockerfile: apps/server/Dockerfile
    env_file:
      - .env
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      PORT: 3000
    restart: unless-stopped
    # no database dependency in file-based mode

  client:
    build:
      context: .
      dockerfile: apps/client/Dockerfile
    depends_on:
      - server
    ports:
      - "5173:80"
    environment:
      NODE_ENV: production
    restart: unless-stopped
